version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/bashotori:cached
      - node-modules-data:/bashotori/node_modules
    ports:
      - 3456:3456
      - 9229:9229
    env_file:
      - ../.env
    working_dir: /bashotori
    tty: true
volumes:
  node-modules-data:
